In [1]:
import pandas as pd

In [2]:
file_path = 'ECB Data Portal_20240109082607.csv'
csv = pd.read_csv(file_path)
csv.head()

,DATE,TIME PERIOD,"Euribor 1-year - Historical close, average of observations through period (FM.M.U2.EUR.RT.MM.EURIBOR1YD_.HSTA)"
0,1994-01-31,1994Jan,6.34
1,1994-02-28,1994Feb,6.42
2,1994-03-31,1994Mar,6.55
3,1994-04-30,1994Apr,6.46
4,1994-05-31,1994May,6.25

In [3]:
csv = csv.drop(["TIME PERIOD"], axis=1)
csv.head()

,DATE,"Euribor 1-year - Historical close, average of observations through period (FM.M.U2.EUR.RT.MM.EURIBOR1YD_.HSTA)"
0,1994-01-31,6.34
1,1994-02-28,6.42
2,1994-03-31,6.55
3,1994-04-30,6.46
4,1994-05-31,6.25

In [ ]:
output_csv_path = "Debt_daily_02.csv"
csv.to_csv(output_csv_path)