In [2]:
import pandas as pd
import calendar

In [3]:
file_path = 'gdp.csv'
df = pd.read_csv(file_path)
df.head()

      Date  GDP_Value
0  2023-10        0.4
1  2023-11        0.4
2  2023-12        0.4

In [14]:
df = df.drop(["TIME PERIOD"], axis=1)
df.head(100)

,DATE,"Euribor 1-year - Historical close, average of observations through period (FM.M.U2.EUR.RT.MM.EURIBOR1YD_.HSTA)"
0,1994-01-31,6.3400
1,1994-02-28,6.4200
2,1994-03-31,6.5500
3,1994-04-30,6.4600
4,1994-05-31,6.2500
...,...,...
95,2001-12-31,3.2981
96,2002-01-31,3.4832
97,2002-02-28,3.5936
98,2002-03-31,3.8156
99,2002-04-30,3.8602

In [5]:
dfs = []

In [7]:
for index, row in df.iterrows():
    monthYear = row[0]
    euribor = row[1]
    year = int(monthYear[0:4])
    month = int(monthYear[5:7])

    is_leap_year = calendar.isleap(year)
    
    start_date = pd.to_datetime(f"{year}-{month}-01")

    if month == 4 or month == 6 or month == 9 or month == 11:
        end_date = pd.to_datetime(f'{year}-{month}-30')
    elif month == 2:
        if is_leap_year:
            end_date = pd.to_datetime(f'{year}-{month}-29')
        else:
            end_date = pd.to_datetime(f'{year}-{month}-28')
    else:
        end_date = pd.to_datetime(f'{year}-{month}-31')
    
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "GDP_value": euribor
        }
    )
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = "GDP_daily.csv"
new_df.to_csv(output_csv_path, index=False)

C:\Users\julga\AppData\Local\Temp\ipykernel_17736\2830182262.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  monthYear = row[0]
C:\Users\julga\AppData\Local\Temp\ipykernel_17736\2830182262.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  euribor = row[1]